### ISSUE TITLE
Questions about image collection

### ISSUE THREAD

**Issue by pedbrgs** [yzyly1992/GloSoFarID#2]
Hello @yzyly1992! I hope this message finds you well.

Firstly, I want to extend my sincere appreciation for your valuable contributions.

I have some inquiries regarding the GloSoFarID image collection process, and I hope you can provide some clarification.

1. In the paper, it is mentioned that 13 bands were collected from Sentinel-2. However, upon reviewing Table 2, I noticed that only 12 bands are listed. Band 10, as depicted in Figure 1, appears to be missing from the table. Could you kindly confirm if this is indeed the case? I found myself puzzled when I came across the dataset link provided in the [README.md](https://github.com/yzyly1992/GloSoFarID/blob/main/README.md?plain=1#L23). It leads to the Harmonized Sentinel-2 MSI Level-2A dataset, which does not include the B10 band. To clarify, were the images collected from the [Harmonized Sentinel-2 MSI Level-2A dataset](https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2_SR_HARMONIZED) (`"COPERNICUS/S2_SR_HARMONIZED"`) or the [Harmonized Sentinel-2 MSI Level-1C dataset](https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2_HARMONIZED) (`"COPERNICUS/S2_HARMONIZED"`)? It's worth noting that the Level-1C dataset includes the B10 band.

2. I would greatly appreciate it if you could share the Python source code used to collect the images from Google Earth Engine. If sharing the code is not possible, could you please provide the parameters utilized in the image collection process? Specifically, I'm interested in details such as scale, maximum number of pixels, cloudy percentage threshold, coordinate reference system (CRS), any filters applied (e.g., date range, area of interest), band order, and any other relevant parameters. I'm making this request because I've trained a segmentation model using the GloSoFarID dataset and have collected additional images here in Brazil to test its generalization. However, I've noticed a significant number of false positives, and I suspect that the issue may be related to the images I've collected. Having access to the source code would greatly assist me in troubleshooting and refining my approach.

Thank you in advance for your assistance.

**Comment by yzyly1992** [comment]
Hello @pedbrgs! Thank you for your questions!

1. You are correct, the dataset are collected from "COPERNICUS/S2_HARMONIZED", which has B10 band. We will revise it soon.
2. Here is a code sample: [colab](https://colab.research.google.com/drive/1aPRsrIMqvVoluzdhWW4N7Lu9DsgEIMXf?usp=sharing) Hope it can help!

**Comment by pedbrgs** [comment]
@yzyly1992 Great! I will try to use it to collect my images. Thanks!
And once again congratulations on the work.
